### ISSUE TITLE
Warning about transformation

### ISSUE THREAD

**Issue by akifh** [cra-ros-pkg/robot_localization#253]
Hi all. I'm running ekf_localization with odom and imu. In console it outputs a warning on transformation about once every 1-2 secs;

```
Node: /ekf_localization
Time: 12:14:21.414057836 (2016-02-02)
Severity: Warn
Published Topics: /diagnostics, /odometry/filtered, /rosout, /tf

WARNING: failed to transform from base_imu_link->base_footprint for imu0 message received at 1454408061.356009006. No transform exists from source to target frame.


Location:
/tmp/buildd/ros-indigo-robot-localization-2.2.1-0trusty-20151111-0737/src/ros_filter.cpp:RosFilter<T>::transformPoseFailureCallback:1547
```

I have checked the tf tree. It seems OK.
![frames](https://cloud.githubusercontent.com/assets/1104239/12746314/bb5e8086-c9a6-11e5-9033-42af51ddf82a.png)

Config for robot_localization is as this;

```
ekf_localization:
  frequency: 50
  odom0: /mobile_base_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, false,
                 false, false, false,
                 false, false, false]
  odom0_differential: false

  imu0: /imu/data_raw
  imu0_config: [false, false, false,
                false, false, true,
                false, false, false,
                false, false, true,
                false, false, false]

  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: odom
  two_d_mode: true
```

Sample IMU msg:

```
header: 
  seq: 54660
  stamp: 
    secs: 1454408422
    nsecs: 461543083
  frame_id: base_imu_link
orientation: 
  x: 0.0646457688177
  y: -0.00454207126069
  z: -0.207613044731
  w: 0.976062046091
orientation_covariance: [0.0025, 0.0, 0.0, 0.0, 0.0025, 0.0, 0.0, 0.0, 0.0025]
angular_velocity: 
  x: 0.0
  y: 0.12
  z: 0.0
angular_velocity_covariance: [0.02, 0.0, 0.0, 0.0, 0.02, 0.0, 0.0, 0.0, 0.02]
linear_acceleration: 
  x: -0.133683359375
  y: 1.04993148437
  z: 8.21060976562
linear_acceleration_covariance: [0.04, 0.0, 0.0, 0.0, 0.04, 0.0, 0.0, 0.0, 0.04]
```

Is this something related with TF frequencies? Should I decrease freq of ekf_localization? I could not figure it out. @ayrton04
