### ISSUE TITLE
SetPose service hangs (sporadically) and CPU usage hits 100%

### ISSUE THREAD

**Issue by spmaniato** [cra-ros-pkg/robot_localization#335]
Hi all,

We (@bhavyangupta and I) are facing the issue described below. We have done some detective work on our side but haven't been able to determine a cause (neither in our setup nor something specific in `robot_localization`) Please take a quick look 🙂 Thanks!

### Issue Description

We are using the EKF node from `rl` and are sporadically observing an issue with the `robot_localization/SetPose` service on `/set_pose`. Specifically, on some occasions that _we cannot replicate_, the service will not respond, causing the calling code to hang. At that point, the EKF node also stops publishing messages on `/odom`. In addition, `top` shows its CPU usage maxing out (normally its usage is around 5-6% and only rarely does it go up to 19% or so):

```
PID USER          PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
860 <user>        20   0   83404   3808   3100 R  97.5  0.4   3:18.65 ekf_localization
```

We dug into the source code (`RosFilter<T>::setPoseCallback`) but didn't find anything obviously suspicious. For example, there's a `while` loop that clears a queue ([ros_filter.cpp#L1826-L1829](https://github.com/cra-ros-pkg/robot_localization/blob/indigo-devel/src/ros_filter.cpp#L1826-L1829)) as well as a bunch of `while` loops elsewhere, but none look like they would run indefinitely 🤔 

### System Setup

This is all taking place on a single-board computer (`armv7hf`) running ROS Indigo for ARM. The `robot_localization` package is installed from Debian packages (i.e. `ros-indigo-robot-localization`). I believe we've seen the issue on both `2.3.0-0trusty-20160728-151324-0700` and `2.3.1-0trusty-20161031-053932-0700` versions (but I'll double-check). The version may be important, as some fixes to `SetPose` were introduced in `2.3.1` (specifically daa6d021451a0894055486bc7eee1f35f4179085) We haven't tried a from-source installation yet.

### EKF Configuration

The EKF is taking in wheel odometry and IMU data (of which only the gyro rate is used):

```yaml
two_d_mode: true
frequency: 20
base_link_frame: 'base_link'
world_frame: 'odom'
odom_frame: 'odom'

odom0: 'odom'
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]

imu0: 'imu'
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              true, true, true,
              false, false, false]
```
