### ISSUE TITLE
Gyro Only Orientation Localization Error

### ISSUE THREAD

**Issue by jwag** [cra-ros-pkg/robot_localization#420]
Hello,

I think I may uncovered an issue with the way robot localization handles gyro data. I am using a Clearpath Jackal robot and the onboard imu which is mounted so that the x-axis faces towards the front of the robot, the y-axis to the left, and the z-axis up. Gyro and accell data is published on the topic /imu/data_raw. The orientation part of the message is set to all zeros with a -1 value for the first covariance.

We tilt the robot in the following way according the base_link:
Forward (+y)
Back to Level (-y)
Right (+x)
Back to Level (-x)
Turn Right 90 deg (-z)
Forward (+y)
Back to Level (-y)
Right (+x)
Back to Level (-x)
Turn Left 90 deg (+z)
Forward (+y)
Back to Level (-y)
Right (+x)
Back to Level (-x)

The resulting /odometry/filtered estimate works correctly before we rotate about the z. Then the tilting results an incorrect orientation. However, we we rotate back to the initial Z orientation the estimate behaves correctly again.

I have attached a bag file with /imu/data, /odometry/filtered, and /tf recorded. I have also attached my robot_localization.yaml file.
[gyro issue.zip](https://github.com/cra-ros-pkg/robot_localization/files/2429648/gyro.issue.zip)

**Comment by ayrton04** [comment]
So I think this should most likely be a question on answers.ros.org, but at the very least, to investigate this, I'll need your full configuration file.

**Comment by ayrton04** [comment]
By the way, for your test, you need to _also_ be fusing linear velocity data. If you only fuse angular velocity data into the filter, your covariance matrices are going to explode (see below), because you're not measuring X, Y, Z, or their velocities. When the covariance matrices explode, it can lead to strange behavior. Not saying that's what's causing this necessarily, but it needs to be corrected before I look at this. You can fake a `TwistWithCovarianceStamped` publisher with all zero values (make sure to set the `frame_id`s in that case).


```
header: 
  seq:       1984
  stamp: 
    secs: 1538063559
    nsecs:  834730387
  frame_id: "odom"
child_frame_id: "base_link"
pose: 
  pose: 
    position: 
      x: 0.00000000
      y: 0.00000000
      z: 0.00000000
    orientation: 
      x: 0.00153258
      y: 0.04461582
      z: 0.12024158
      w: 0.99174041
  covariance: [25197.5189, 126.556763, -1506.5567, 0.00000000, 0.00000000, 0.00000000, 126.556763, 25794.6695, 1465.96571, 0.00000000, 0.00000000, 0.00000000, -1506.5567, 1465.96571, 70256.0844, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.87387033, -0.0149394, 0.35134912, 0.00000000, 0.00000000, 0.00000000, -0.0149394, 0.89123394, -0.0390019, 0.00000000, 0.00000000, 0.00000000, 0.35134912, -0.0390019, 2.62323192]
twist: 
  twist: 
    linear: 
      x: 0.00000000
      y: 0.00000000
      z: 0.00000000
    angular: 
      x: -0.0124698
      y: -0.2889042
      z: 0.00103422
  covariance: [210.684183, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 210.684183, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 316.125730, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000012, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000012, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000012]
```
