### ISSUE TITLE
navsat_transform uses "odom" for /tf_static

### ISSUE THREAD

**Issue by Timple** [cra-ros-pkg/robot_localization#453]
The static_transform provided by navsat_transform uses the odom frame.
On our robot however we do not use this frame at all.

I can see it being initialized here:
https://github.com/cra-ros-pkg/robot_localization/blob/2b57df66ded98b3ae4d08176f54beead4e9e1f5f/src/navsat_transform.cpp#L65

But it should be overwritten here:
https://github.com/cra-ros-pkg/robot_localization/blob/2b57df66ded98b3ae4d08176f54beead4e9e1f5f/src/navsat_transform.cpp#L549

But I have no idea why this does not happen. We do specify the datum manually (which might be a bit un-standard). 

Relevant config:
```yaml
ekf_se_map:
  frequency: 20
  two_d_mode: true

  map_frame: unused
  odom_frame: map
  base_link_frame: base_link

  world_frame: map

  odom0: odometry/gps
  odom0_config: [true,  true,  true,  # X,Y,Z,
                 false, false, false, # roll,pitch,yaw,
                 false, false, false, # X`,Y`,Z`,
                 false, false, false, # roll`,pitch`,yaw`,
                 false, false, false] # X``,Y``,Z``
  odom0_queue_size: 3
  odom0_nodelay: true
  odom0_differential: false
  odom0_relative: false

  imu0: imu/data
  imu0_config: [false, false, false,  # X,Y,Z,
                true, true,  true,   # roll,pitch,yaw,
                false, false, false,  # X`,Y`,Z`,
                false, false,  true,   # roll`,pitch`,yaw`,
                false, false, false]   # X``,Y``,Z``
  imu0_nodelay: true
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 30  # Use all data from imu although we run at lower frequency
  imu0_remove_gravitational_acceleration: true
  imu0_gravitational_acceleration: 9.812

  use_control: false

navsat_transform:
  frame_id: gps
  frequency: 10
  delay: 1.0
  yaw_offset: 0
  broadcast_utm_transform: true
  use_odometry_yaw: true
  wait_for_datum: true
```
