### ISSUE TITLE
ROS2 Foxy /fromLL giving all 0s

### ISSUE THREAD

**Issue by sisaha9** [cra-ros-pkg/robot_localization#658]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Binaries

#### Steps to reproduce issue
- Run navsat_transform node to set up fromLL and toLL services
- In a terminal type: 
```bash
ros2 service call /fromLL robot_localization/srv/FromLL "ll_point:
  latitude: 42.4373
  longitude: -86.9436
  altitude: 0.2703"
```
- Then type: 
```bash
ros2 service call /fromLL robot_localization/srv/FromLL "ll_point:
  latitude: 40.4373
  longitude: -86.9436
  altitude: 0.2703"
```

#### Expected behavior
One of the coordinates change due to the changed latitude

#### Actual behavior
All of X, Y and Z stay at 0

```bash
requester: making request: robot_localization.srv.FromLL_Request(ll_point=geographic_msgs.msg.GeoPoint(latitude=42.4373, longitude=-86.9436, altitude=0.2703))

response:
robot_localization.srv.FromLL_Response(map_point=geometry_msgs.msg.Point(x=0.0, y=0.0, z=0.0))
```

```bash
requester: making request: robot_localization.srv.FromLL_Request(ll_point=geographic_msgs.msg.GeoPoint(latitude=40.4373, longitude=-86.9436, altitude=0.2703))

response:
robot_localization.srv.FromLL_Response(map_point=geometry_msgs.msg.Point(x=0.0, y=0.0, z=0.0))

```

#### Additional information
My navsat transform node:
Launch file:
```python
from launch import LaunchDescription
from launch_ros.actions import Node
import os
from ament_index_python.packages import get_package_share_directory

def generate_launch_description():
    gps_nav_dir = get_package_share_directory('gps_nav')
    parameters_file_dir = os.path.join(gps_nav_dir, 'params')
    parameters_file_path = os.path.join(parameters_file_dir, 'gps_to_xyz.yaml')
    return LaunchDescription([
    	Node(
            package='robot_localization',
            executable='navsat_transform_node',
            name='navsat_transform_node',
            parameters=[parameters_file_path],
            remappings=[
                ('imu/data', '/imu/imu_raw'),
                ('gps/fix', '/gnss/fix'),
                ('odometry/filtered', '/lgsvl/gnss_odom')
            ]
        )
    ])
```
YAML file:
```yaml
navsat_transform_node:
    ros__parameters:
        frequency: 30.0
        magnetic_declination_radians: 0.0   
        yaw_offset: 0.0  
        zero_altitude: false
        publish_filtered_gps: true
        use_odometry_yaw: false
        broadcast_utm_transform: true
        broadcast_utm_transform_as_parent_frame: true
```

I can confirm the topics are all working and outputting right information. One odd thing is if I use 

```bash
ros2 node info /navsat_transform_node
```
 it shows it's subscribed to "/imu" instead of "/imu/imu_raw". But in my launch file I have set it to "/imu/imu_raw" so not sure why that is. I am using the [SVL simulator](http://svlsimulator.com/) with the Lexus2016RXHybrid and Autoware.Auto sensor configuration but I don't think it's the issue since the data getting outputted is right
