### ISSUE TITLE
Yaw Integration Issues?

### ISSUE THREAD

**Issue by yishaiSilver** [cra-ros-pkg/robot_localization#885]
Hello, I am struggling to integrate a magnetometer into my robot. I noticed that for the following lines, the yaw isn't being used from the IMU. Is this by mistake, or perhaps a difference from the Nav2 documentation?

https://github.com/cra-ros-pkg/robot_localization/blob/f2b36f761ffd6f7b07c98b6c748c4d75660098b9/params/dual_ekf_navsat_example.yaml#L82C19-L82C39

As for my integration issue, I do not see any reasonable yaw for my robot. Excluding the yaw from the wheel odometry on both the local and global level, I only see a slow spinning behavior. My magnetometer is calibrated, its values look reasonable, and I am publishing an IMU message as echoed under /magnet:
```
header:
  stamp:
    sec: 1716233752
    nanosec: 205227613
  frame_id: imu
orientation:
  x: 0.0
  y: 0.0
  z: -0.452924548806447
  w: 1.0
orientation_covariance:
- -1.0
- 0.0
- 0.0
- 0.0
- -1.0
- 0.0
- 0.0
- 0.0
- 1.0
```

And I'm integrating it in my yaml file as follows:
```
imu0: /magnet
imu0_config: [false, false, false,
            false,  false,  true, # _, _, yaw
            false, false, false,
            false,  false,  false,
            false,  false,  false]
imu0_differential: false 
imu0_relative: false
imu0_queue_size: 10
```
