### ISSUE TITLE
 High CPU Usage with navsat_transform Node in ROS 2 Jazzy

### ISSUE THREAD

**Issue by porizou** [cra-ros-pkg/robot_localization#890]
I am experiencing an issue where the navsat_transform node in ROS 2 Jazzy consistently causes the CPU usage to exceed 100%. This occurs during normal operation and significantly impacts system performance. Here are the details of my setup:

System Information:

- OS: Ubuntu 24.04LTS
- ROS 2 : Jazzy
- navsat_transform package version: 3.8.0

parameter of navsat_transform_node

```yaml
navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    delay: 3.0
    yaw_offset: 1.57
    magnetic_declination_radians: 0.0
    zero_altitude: true
    broadcast_utm_transform: false
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
```

![image](https://github.com/cra-ros-pkg/robot_localization/assets/14184141/26f86666-1001-404b-9aa5-14d03c114dea)
