### ISSUE TITLE
navsat_transform: "Could not obtain [map_frame] -> [base_link_frame] transform. Will not remove offset of navsat device from robot's origin"

### ISSUE THREAD

**Issue by vlacorre** [cra-ros-pkg/robot_localization#905]
Hi,

### **Desktop:**
 - OS: Ubuntu 22.04
 - ROS Distribution: ROS 2 Humble
 - `robot_localization` Package Version: 3.5.3

### **Description of the bug**
Sensor inputs:
- GNSS receiver: publishes NavSatFix on topic /ublox_gps_node/fix

Running nodes:
- my_odom_node: 
  - publishes odometry{parent: "**odom**", child: "**aft_mapped**"} on topic **/aft_mapped_to_init**
  - publishes transform{**odom** -> **aft_mapped**} on topic /tf
- navsat_transform_node: (configuration given below)
- ekf_node: (configuration given below)

**Launch configuration:**

```python
    # Grabs GNSS fix (and /odometry/global for redundancy) and publishes on /odometry/gps --> [frame_id = map | no child]
    gnss_fix_to_odometry_node = Node(
          package="robot_localization",
          executable="navsat_transform_node",
          name="navsat_transform",
          output="screen",
          parameters=[rl_params_file, {"use_sim_time": False}],
          remappings=[
              ("odometry/filtered", "odometry/global"), # IN
              ("gps/fix", "/ublox_gps_node/fix"),           # IN

              ("odometry/gps", "odometry/gps"),         # OUT
          ],
      )

    local_global_odometry_EKF_node = Node(
        package="robot_localization",
        executable="ekf_node",
        name="ekf_filter_node_map",
        parameters=[rl_params_file, {"use_sim_time": False}],
        remappings=[("odometry/filtered", "odometry/global")],
    )
```

**robot_localization configuration (rl_params_file):**

```yaml
navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 4.0 # Seconds to wait before calculating the transform from GPS coordinates to your robot’s world frame.

    zero_altitude: false
    yaw_offset: 0.0

    broadcast_utm_transform: false
    publish_filtered_gps: false

    wait_for_datum: true
    datum: [59.6099, 16.5448, 0.0] #  latitude, longitude, heading (in radians)
    # Note: A heading of 0 is toward the east, positive is counter-clockwise.


ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    print_diagnostics: true
    debug: true
    publish_tf: true
    use_control: false

    map_frame: map
    odom_frame: odom # r3live publishes the odometry in the "world" frame instead of the "odom" frame

    world_frame: map

    base_link_frame: aft_mapped # r3live publishes the odometry of the "aft_mapped" frame on the topic "/aft_mapped_to_init"

    # Directly use roll, pitch and yaw 
    odom0: aft_mapped_to_init
    odom0_config: [false, false, false,
                  true,  true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # Differentiate X, Y and Z  to get linear velocities and avoid conflicts with the GNSS fix.
    odom1: aft_mapped_to_init
    odom1_config: [true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: true
    odom1_relative: false

    # Fully use the GNSS fix
    odom2: odometry/gps
    odom2_config: [true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom2_queue_size: 10
    odom2_differential: false
    odom2_relative: false

    process_noise_covariance: [1.0,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    1.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    1e-3,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.3,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.3,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.5,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.5,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.1,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.3,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.3,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.3,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.3,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.3,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.3]
```

### **Observed topic messages**

**ros2 topic echo /aft_mapped_to_init**
```
header:
  stamp:
    sec: 1726739722
    nanosec: 790758797
  frame_id: odom
child_frame_id: aft_mapped
pose:
  pose:
    position:
      x: 0.10258937213147493
      y: 2.7701529127127364
      z: 0.024107572558434473
    orientation:
      x: -8.282671855659729e-06
      y: -0.009924303899904296
      z: 0.6448299265475481
      w: 0.7642616528075862
  covariance:...
twist:
  twist:
    linear:
      x: 0.044240643416767325
      y: 0.6249538835056032
      z: 0.08919482097844317
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  covariance:...
```

**ros2 topic echo /odometry/global**
```
header:
  stamp:
    sec: 1726739822
    nanosec: 348192361
  frame_id: map
child_frame_id: aft_mapped
pose:
  pose:
    position:
      x: -0.25974070818647876
      y: 0.19798858059338026
      z: -1.7405198023880515
    orientation:
      x: -0.03348903951968671
      y: -0.08314526315978304
      z: -0.9451438254890524
      w: 0.31411542239447443
  covariance:...
twist:
  twist:
    linear:
      x: 0.1696467914398178
      y: 0.014912242395973692
      z: 0.048012318595715454
    angular:
      x: -0.01823663157281553
      y: 0.008895651118444689
      z: 0.7269163760872626
  covariance:...
```

**ros2 topic echo /tf**
```
transforms:
- header:
    stamp:
      sec: 1726663091
      nanosec: 867570688
    frame_id: odom
  child_frame_id: aft_mapped
  transform:
    translation:
      x: -0.6022346466302645
      y: -0.4813953435053505
      z: 0.04574495798068348
    rotation:
      x: 0.00692517750300668
      y: -0.004017908657183388
      z: 0.29452136667764633
      w: 0.9556113555713461
---
transforms:
- header:
    stamp:
      sec: 1726740012
      nanosec: 400888082
    frame_id: map
  child_frame_id: odom
  transform:
    translation:
      x: -0.08354226009412274
      y: 0.43476403067130615
      z: -0.037945088323984674
    rotation:
      x: 0.004705087695066744
      y: -0.003720210643958476
      z: 0.4770191784565508
      w: 0.8788724171159222
```

### **Output**
When starting everything, I get this error message:

> [navsat_transform_node-5] [ERROR] [1726738973.601752606] [navsat_transform]: 
> Could not obtain map -> aft_mapped transform. Will not remove offset of navsat device from robot's origin

### **Expected behavior**
From what I understand, navsat_transform_node is expecting a map -> aft_mapped tf, but this transform is actually provided in two parts:
1. odom -> aft_mapped (given by my_odom_node)
2. map -> odom (given by ekf_filter_node_map)

So is it a bug that navsat_transform_node complains about not having "map -> aft_mapped"?
