### ISSUE TITLE
UKF NaNs

### ISSUE THREAD

**Issue by rayferric** [cra-ros-pkg/robot_localization#906]
## Describe the bug
After [#751](https://github.com/cra-ros-pkg/robot_localization/pull/751) was merged, the Unscented Kalman Filter starts producing NaN values within about 5 seconds when the simulation is paused, and no new sensor readings are being published.

Once this happens, this message will appear:

https://github.com/cra-ros-pkg/robot_localization/blob/ef0a27352962c56a970f2bbeb8687313b9e54a9a/src/ros_filter.cpp#L2157-L2163

...and then the terminal will be flooded with TF NaN errors.

This issue does not occur when using the Extended Kalman Filter.

## To Reproduce
1. Run a simulated robot and launch robot_localization.
2. The filter will properly work and estimate the position as usual.
3. Pause the simulation so that no new sensor data is received, also attempt driving around or resuming a few times.
4. At some point a load of TF NaN errors will appear in the terminal.

## Expected behavior
The UKF should never produce NaN values.

## Desktop (please complete the following information):
- OS: Ubuntu 24.04.1 LTS
- ROS Distribution: Jazzy
- `robot_localization` Package Version: `jazzy-devel` @ 0cd2e468493325754bd1e7add7384df75d9f1658 Added subscription to stamped topic

## Additional context
We are currently using the EKF as a workaround. Below is the UKF configuration we used on Humble without issues:

```yaml
/**:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: false
    debug: false
    permit_corrected_publication: false
    publish_acceleration: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

{% for camera_id in rgbd_ids %}
    odom{{ loop.index0 }}: {{ camera_id }}/odom
    odom{{ loop.index0 }}_config: [false, false, false,
                                   false, false, false,
                                   true,  true,  true,
                                   true,  true,  true,
                                   false, false, false]
    odom{{ loop.index0 }}_queue_size: 10
    odom{{ loop.index0 }}_differential: false
    odom{{ loop.index0 }}_relative: false
{% endfor %}

    imu0: imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false

    process_noise_covariance: [
      0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  10.0, 0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  10.0, 0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  10.0, 0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025, 0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.025, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.04, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.02, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015
    ]
    # NOTE: Setting 10.0 back to 0.03 did not help with the NaNs.
```

### Regarding Deprecation

In the issue template I also noticed the comment mentioning that the robot_localization package will soon be deprecated. This package is widely used and popular in the ROS community, so I have trouble understanding why it is being deprecated? Is there a planned replacement?

**Comment by ayrton04** [comment]
Please ask this as a question on robotics.stackexchange.com. When you do, please include a sample message from every sensor input. While there's always a first time, I have yet to see a case of NaN values that weren't the result of bad inputs or misconfiguration.

Also, the community is moving towards [fuse](https://github.com/locusrobotics/fuse), hence the eventual deprecation of this package.

**Comment by peci1** [comment]
I have this snippet from debug log which points at some obvious wrong handling of RPY angles:

```
Corrected full state is:
[0.00083795  1.7756e-05  5.1589e-11  -0.092073   0.17038     2.3513      -3.9835e-08 4.4462e-08  -1.65e-08   8.53e-06    0.00058345  -0.00059024 -1.3339e-10 1.4886e-10  -5.5425e-11 ]

Corrected full estimate error covariance is:
[10.001      2.9755e-08  -1.0978e-12 4.331e-10   -9.8852e-10 2106        6.5841e-05  -1.0416e-06 1.128e-05   -1.2211e-11 9.2627e-11  1.4086e-11  2.199e-07   -3.4788e-09 3.7674e-08
 2.9755e-08  10.001      4.0408e-12  -4.3386e-10 3.002e-09   44.606      1.107e-12   6.6525e-05  6.1428e-06  2.6682e-10  -4.0933e-10 -5.2967e-11 3.9486e-15  2.2219e-07  2.0517e-08  
 -1.0978e-12 4.0408e-12  100         5.0454e-10  -2.5994e-09 0.0056063   -1.1328e-05 -6.0538e-06 6.5562e-05  -2.123e-10  3.5161e-10  4.5532e-11  -3.7835e-08 -2.022e-08  2.1897e-07
 4.331e-10   -4.3386e-10 5.0454e-10  0.00039759  -7.2401e-06 -20.372     -4.9154e-11 6.5428e-11  8.7398e-11  1.1417e-05  3.0117e-06  1.4771e-07  -8.5973e-13 9.5949e-13  -3.5728e-13
 -9.8852e-10 3.002e-09   -2.5994e-09 -7.2401e-06 0.00043346  81.509      -7.7981e-10 8.1588e-10  -8.7883e-10 3.0302e-06  6.9239e-06  -7.6004e-07 9.8348e-13  -1.0976e-12 4.0886e-13
 2106        44.606      0.0056063   -20.372     81.509      -1.0052e+09 -52.761     58.885      -21.885     10628       7.6745e+05  -7.7739e+05 -0.17647    0.19694     -0.073326
 6.5841e-05  1.107e-12   -1.1328e-05 -4.9154e-11 -7.7981e-10 -52.761     0.00024727  3.0505e-06  -1.1337e-06 0.00055054  0.039758    -0.040273   -9.1402e-09 1.0202e-08  -3.7983e-09
 -1.0416e-06 6.6525e-05  -6.0538e-06 6.5428e-11  8.1588e-10  58.885      3.0505e-06  0.0002466   1.2654e-06  -0.00061445 -0.044373   0.044948    1.0203e-08  -1.1385e-08 4.2396e-09
 1.128e-05   6.1428e-06  6.5562e-05  8.7398e-11  -8.7883e-10 -21.885     -1.1337e-06 1.2654e-06  0.00039953  0.00022836  0.016491    -0.016705   -3.7917e-09 4.232e-09   -1.5754e-09
 -1.2211e-11 2.6682e-10  -2.123e-10  1.1417e-05  3.0302e-06  10628       0.00055054  -0.00061445 0.00022836  -0.11079    -8.0083     8.112       1.8414e-06  -2.055e-06  7.6513e-07
 9.2627e-11  -4.0933e-10 3.5161e-10  3.0117e-06  6.9239e-06  7.6745e+05  0.039758    -0.044373   0.016491    -8.0083     -578.32     585.82      0.00013298  -0.0001484  5.5255e-05
 1.4086e-11  -5.2967e-11 4.5532e-11  1.4771e-07  -7.6004e-07 -7.7739e+05 -0.040273   0.044948    -0.016705   8.112       585.82      -593.41     -0.0001347  0.00015032  -5.5971e-05
 2.199e-07   3.9486e-15  -3.7835e-08 -8.5973e-13 9.8348e-13  -0.17647    -9.1402e-09 1.0203e-08  -3.7917e-09 1.8414e-06  0.00013298  -0.0001347  0.0001      3.4122e-11  -1.2704e-11
 -3.4788e-09 2.2219e-07  -2.022e-08  9.5949e-13  -1.0976e-12 0.19694     1.0202e-08  -1.1385e-08 4.232e-09   -2.055e-06  -0.0001484  0.00015032  3.4122e-11  0.0001      1.4179e-11
 3.7674e-08  2.0517e-08  2.1897e-07  -3.5728e-13 4.0886e-13  -0.073326   -3.7983e-09 4.2396e-09  -1.5754e-09 7.6513e-07  5.5255e-05  -5.5971e-05 -1.2704e-11 1.4179e-11  0.00015     ]
 
 
---------------------- /Ukf::correct ----------------------  
------ /FilterBase::processMeasurement (imu0_twist) ------   
------ FilterBase::processMeasurement (imu0_twist) ------
Filter is already initialized. Carrying out predict/correct loop...
Measurement time is 1749820672377000093, last measurement time is 1749820672367000102, delta is 9999991
---------------------- Ukf::predict ----------------------
delta is 0.0099999909999999997412
state is [0.00083795  1.7756e-05  5.1589e-11  -0.092073   0.17038     2.3513      -3.9835e-08 4.4462e-08  -1.65e-08   8.53e-06    0.00058345  -0.00059024 -1.3339e-10 1.4886e-10  -5.5425e-11 ]

Predicted state is:
[0.76941     -0.0036469  -7.3046e-11 3.0495      -2.9712     -0.79034    -3.9836e-08 4.4463e-08  -1.6501e-08 8.53e-06    0.00058345  -0.00059024 -1.3339e-10 1.4886e-10  -5.5425e-11 ]

Predicted estimate error covariance is:
[11.183      -0.005634   2.9608e-09  1.2877e+06  -1.9291e+06 1.9312e+06  6.671e-05   -2.01e-06   1.164e-05   -0.00017478 -0.01262    0.012784    2.2281e-07  -6.7173e-09 3.888e-08
 -0.005634   10.002      6.0151e-07  -6140.9     6645.7      -11730      0.00017763  -0.00013172 7.9824e-05  -0.035781   -2.5836     2.6171      5.9408e-07  -4.4081e-07 2.6737e-07
 2.9607e-09  6.0151e-07  100         -0.55769    8112.1      -8111.2     0.00013008  -0.00016388 0.00012422  -0.028485   -2.0568     2.0835      4.3511e-07  -5.4803e-07 4.1549e-07
 1.2877e+06  -6140.9     -0.55769    -8442.1     5.2896e+06  -4.7196e+06 -164.69     183.81      -68.315     33175       2.3973e+06  -2.4303e+06 -0.55166    0.61566     -0.22923
 -1.9291e+06 6645.7      8112.1      5.2896e+06  -42837      5.4936e+06  160.29      -178.9      66.489      -32286      -2.3331e+06 2.3615e+06  0.5361      -0.59829    0.22276
 1.9312e+06  -11730      -8111.2     -4.7196e+06 5.4936e+06  -2.302e+06  104.65      -116.82     43.404      -21081      -1.5204e+06 1.5382e+06  0.34916     -0.38973    0.14506
 6.671e-05   0.00017763  0.00013008  -164.69     160.29      104.65      0.042008    -0.046606   0.017322    -8.4117     -607.39     615.26      0.00013966  -0.00015586 5.8033e-05
 -2.01e-06   -0.00013172 -0.00016388 183.81      -178.9      -116.82     -0.046606   0.052266    -0.019332   9.3882      677.89      -686.68     -0.00015587 0.00017396  -6.4769e-05
 1.164e-05   7.9824e-05  0.00012422  -68.315     66.489      43.404      0.017322    -0.019332   0.007585    -3.4892     -251.95     255.21      5.7932e-05  -6.4653e-05 2.4072e-05
 -0.00017478 -0.035781   -0.028485   33175       -32286      -21081      -8.4117     9.3882      -3.4892     1694.4      1.2235e+05  -1.2394e+05 -0.028133   0.031397    -0.01169
 -0.01262    -2.5836     -2.0568     2.3973e+06  -2.3331e+06 -1.5204e+06 -607.39     677.89      -251.95     1.2235e+05  8.8346e+06  -8.9491e+06 -2.0314     2.2671      -0.84411
 0.012784    2.6171      2.0835      -2.4303e+06 2.3615e+06  1.5382e+06  615.26      -686.68     255.21      -1.2394e+05 -8.9491e+06 9.0651e+06  2.0577      -2.2965     0.85504
 2.2281e-07  5.9408e-07  4.3511e-07  -0.55166    0.5361      0.34916     0.00013966  -0.00015587 5.7932e-05  -0.028133   -2.0314     2.0577      0.00010047  -5.2129e-07 1.9409e-07
 -6.7173e-09 -4.4081e-07 -5.4803e-07 0.61566     -0.59829    -0.38973    -0.00015586 0.00017396  -6.4653e-05 0.031397    2.2671      -2.2965     -5.2129e-07 0.00010058  -2.1661e-07
 3.888e-08   2.6737e-07  4.1549e-07  -0.22923    0.22276     0.14506     5.8033e-05  -6.4769e-05 2.4072e-05  -0.01169    -0.84411    0.85504     1.9409e-07  -2.1661e-07 0.00015008  ]


--------------------- /Ukf::predict ----------------------
```

Looking at just the angles:

```
state is [-0.092073   0.17038     2.3513 ]
predicted state is [3.0495      -2.9712     -0.79034 ]
```

The robot was standing still...

**Comment by ayrton04** [comment]
Yeah, the UKF needs some love. Thanks for the logs.

**Comment by ayrton04** [comment]
Does anyone here have any bags that I might use to test this?

**Comment by peci1** [comment]
This bag with the following config goes to NaNs in the first second with UKF:

https://filesender.cesnet.cz/?s=download&token=b89bcd74-4f27-49cc-922c-07b3fd684d5c

```YAML
ekf_localization:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: local_odom
    base_link_frame: base_link
    world_frame: local_odom  # world_frame == map_frame => work in map mode

    two_d_mode: false  # FOR NOW 2D ONLY

    predict_to_current_time: false
    smooth_lagged_data: false
    history_length: 0.0

    initial_estimate_covariance: [1e1, 1e1, 1e2, 1e2, 1e2, 1e2, 1e-2, 1e-2, 1e-2, 1e-2, 1e-2, 1e-2, 1e-2, 1e-2, 1e-2]
    dynamic_process_noise_covariance: false

    print_diagnostics: true
    debug: true
    debug_out_file: /tmp/rl.log

    frequency: 20.

    odom0: odom_2d_new
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, false,
                  false, false, false]
    odom0_differential: false
    odom0_queue_size: 50

    odom1: odom/visual
    odom1_config: [false, false, false,
                  false, false, false,
                  true, true, true,
                  false, false, true,
                  false, false, false]
    odom1_differential: false
    odom1_queue_size: 10

    imu0: imu/data
    imu0_config: [false, false, false,
                  true, true, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false
    imu0_queue_size: 100
```
